In [5]:
%load_ext autoreload
%autoreload 2
import pandas as pd
from Data import LIARDataPoint, LIARDataset
import string
from tqdm.notebook import tqdm
import numpy as np
from utils import Vocab, add_file_to_vocab
import h5py
import json

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
with open("words2idx.json", 'r') as f:
    word2id = json.load(f)
    
with open("speaker2idx.json", 'r') as f:
    speaker2idx = json.load(f)
    
    
with open("party2idx.json", 'r') as f:
    party2idx = json.load(f)
    
    
with open("state2idx.json", 'r') as f:
    state2idx = json.load(f)

In [110]:
dataset = LIARDataset('Data/train.tsv',  word2id, speaker2idx, state2idx, party2idx)

In [112]:
dataset[10]

([[10,
   0,
   58,
   79,
   6,
   299,
   0,
   593,
   3,
   0,
   121,
   814,
   538,
   3773,
   14,
   1776,
   73,
   0,
   5894,
   538,
   3773,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1,
   -1],
  'elections',
  9,
  'U.S. Senator',
  6,
  1,
  'a speech'],
 'mostly-true')

In [90]:
file = open('Data/train.tsv','r', encoding='utf-8')
speaker2idx = {}
for line in file:
    l = line.rstrip('\n').split('\t')
    speaker = l[6]
    if speaker not in speaker2idx.keys():
        speaker2idx[speaker] = len(speaker2idx.keys())
file.close()
print(len(speaker2idx))

# with open("party2idx.json", "w") as f:
#     f.write(json.dumps(speaker2idx))

[autoreload of Data.Dataset failed: Traceback (most recent call last):
  File "C:\Users\seanj\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\seanj\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 450, in superreload
    update_generic(old_obj, new_obj)
  File "C:\Users\seanj\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 387, in update_generic
    update(a, b)
  File "C:\Users\seanj\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 357, in update_class
    update_instances(old, new)
  File "C:\Users\seanj\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "C:\Users\seanj\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 317, in update_instances
    update_instances(old, new, obj, visited)
  File "C:\Users\seanj\Anaconda3\li

23


In [28]:
values

{'',
 'Fox\'s "The O\'Reilly Factor"',
 'an e-mail message sent to voters before Super Tuesday.',
 'a speech in the U.S. Senate',
 "an interview on Univision's 'Al Punto'",
 'an article in The Oregonian',
 'a debate in Jacksonville, Fla.',
 'social media postings',
 'a Republican debate on Fox Business Network in South Carolina on Fox Business Network ',
 "a comment on Newsweek magazine's Web site ",
 "an interview on Fox's 'Hannity'",
 'Miami Herald editorial board interview',
 'a Pew Research Center poll',
 'Alexander Snitker in a campaign press release',
 'a panel discussion',
 'an essay in The Hollywood Reporter',
 'an email and social media posts',
 'a meeting with reporters and editors',
 'an op-ed column',
 'a Republican presidential debate in Tampa',
 'a city council meeting',
 'a rally at the Democratic National Convention',
 'a TV campaign commercial',
 'Associated Press Annual Meeting, Washington D.C.',
 'a congressional briefing',
 'an online campaign commercial ',
 'a pres

In [2]:
glove = set()
with open("utils/glove.6B.50d.txt", 'r', encoding='utf-8') as f:
    i =1 
    in_vocab = 0
    out = 0
    for line in tqdm(f):
        i+=1
        word = line.split(" ")
        glove.add(word[0])


In [83]:


def generate_embedding_matrix(embedding_file, input_file, emb_size = 50):
    vocab = Vocab()
    vecs = [np.random.normal(scale =.5, size = (emb_size))]
    print(len(vecs))
    with open(embedding_file, 'r', encoding='utf-8') as f:
        for line in tqdm(f):
            l = line.split()
            vocab.add(l[0])
            vecs.append(np.array(l[1:]).astype(float))
    
    glove_words = len(vecs)
    print("GLove words:", glove_words)
    vocab = add_file_to_vocab(vocab, input_file)
    new_words = len(vocab) - glove_words
    print("new words:", new_words)
    for i in range(new_words):
        vecs.append(np.random.normal(scale =.5, size = (emb_size)))
    print(len(vecs), len(vocab))
    vocab.add("<UNK>")
    vecs.append(np.random.normal(scale =.5, size = (emb_size)))
    print(len(vecs), len(vocab))
    return vocab, vecs
        

In [84]:
v, vecs = generate_embedding_matrix("utils/glove.6B.50d.txt", "Data/train.tsv")

1



GLove words: 400001
new words: 1317
401318 401318
401319 401319


In [90]:
vectors= np.vstack(vecs)
print(vectors.shape, vectors[0] == vecs[0])

(401319, 50) [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]


In [93]:
vecs[v.word2id['the']]

array([ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
       -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
        2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
        1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
       -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
       -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
        4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
        7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
       -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
        1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01])

In [98]:
with h5py.File("embedding_data.hdf5", "w") as f:
    f.create_dataset('embeddings', data = vectors)

In [96]:
with open('words2idx.json', 'w') as f:
    f.write(json.dumps(v.word2id))

In [94]:
vecs[v.word2id['<UNK>']]

array([-0.08314272,  0.78836429, -0.03987157, -0.35317125, -0.10759101,
        0.08349228,  0.26999295,  0.56719346, -0.01432633, -0.65225478,
        1.03855806,  0.46936216, -0.11568153, -0.07700343,  0.11098086,
        0.53325444,  0.62334181, -0.34828129, -0.28702685,  0.1371722 ,
       -0.6683764 ,  0.70060986,  0.21618649, -0.00540179,  0.53601556,
       -0.95921513, -0.78422833, -1.12431245,  0.04832206, -0.07006286,
       -0.15517307, -0.47597446, -0.41462358,  0.5083193 , -0.58668856,
       -0.46241408, -0.19046496,  0.29989789,  0.55411851, -1.01116461,
       -0.42375192,  0.01119594,  0.99887071, -0.00445543,  0.20686114,
        0.28659336,  0.47433998, -0.68337548,  1.40221129, -0.0226838 ])

In [63]:
len(vecs)

401318

In [97]:
with h5py.File("embeddig_data.hdf5", "r") as f:
    dset = f['.']['embeddings'].value

OSError: Unable to open file (unable to open file: name = 'embedding_data.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [99]:
with h5py.File("embedding_data.hdf5", "r") as f:
            weights3 = f['.']['embeddings'].value

In [101]:
weights3[v.word2id['<UNK>']]

array([-0.08314272,  0.78836429, -0.03987157, -0.35317125, -0.10759101,
        0.08349228,  0.26999295,  0.56719346, -0.01432633, -0.65225478,
        1.03855806,  0.46936216, -0.11568153, -0.07700343,  0.11098086,
        0.53325444,  0.62334181, -0.34828129, -0.28702685,  0.1371722 ,
       -0.6683764 ,  0.70060986,  0.21618649, -0.00540179,  0.53601556,
       -0.95921513, -0.78422833, -1.12431245,  0.04832206, -0.07006286,
       -0.15517307, -0.47597446, -0.41462358,  0.5083193 , -0.58668856,
       -0.46241408, -0.19046496,  0.29989789,  0.55411851, -1.01116461,
       -0.42375192,  0.01119594,  0.99887071, -0.00445543,  0.20686114,
        0.28659336,  0.47433998, -0.68337548,  1.40221129, -0.0226838 ])